#!/usr/bin/env node
/* ============================================================
   build-sitemap.js
   ------------------------------------------------------------
   Regenerates sitemap.xml from the pages actually on disk, so it
   can never drift from the site.

   Dynamic in three ways:
     - the URL list is read from the filesystem, not a hard-coded array
     - <lastmod> is each file's real modification date
     - <priority> / <changefreq> come from assets/data/seo.js, the same
       file that feeds the <head> of every page

   Run it after adding, renaming or editing a page:

       node tools/build-sitemap.js
   ============================================================ */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SEO = require(path.join(ROOT, 'assets/data/seo.js'));
const SITE = SEO.site;

/* Pages that must never appear in search results */
const SKIP = new Set([
  'googlef60eb449e06e57e3.html' // Search Console ownership proof
]);

/* Folders whose .html files are real pages */
const DIRS = ['details', 'designdetail', 'service'];

/* ------------------------------------------------------------
   Helpers
   ------------------------------------------------------------ */

/* Real modification date of the file, as YYYY-MM-DD */
function lastmod(rel) {
  const stat = fs.statSync(path.join(ROOT, rel));
  return stat.mtime.toISOString().slice(0, 10);
}

const enc = (p) => p.split('/').map(encodeURIComponent).join('/');

/* Anything not described in seo.js is still a real page — give it
   sane defaults rather than dropping it from the sitemap. */
function settingsFor(rel) {
  const cfg = SEO.pages[rel];
  if (cfg) return { priority: cfg.priority || '0.7', changefreq: cfg.changefreq || 'monthly' };
  return { priority: SEO.caseStudy.priority, changefreq: SEO.caseStudy.changefreq };
}

/* ------------------------------------------------------------
   Collect
   ------------------------------------------------------------ */

const files = [];

['index.html', 'projects.html', 'docs.html'].forEach((f) => {
  if (fs.existsSync(path.join(ROOT, f))) files.push(f);
});

DIRS.forEach((dir) => {
  fs.readdirSync(path.join(ROOT, dir))
    .filter((f) => f.endsWith('.html') && !SKIP.has(f))
    .sort()
    .forEach((f) => files.push(dir + '/' + f));
});

const urls = files
  .filter((f) => !SKIP.has(f))
  .map((f) => {
    const s = settingsFor(f);
    return {
      loc: SITE + (f === 'index.html' ? '' : enc(f)),
      lastmod: lastmod(f),
      changefreq: s.changefreq,
      priority: s.priority
    };
  });

/* ------------------------------------------------------------
   Write
   ------------------------------------------------------------ */

const xml =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<!-- Generated by tools/build-sitemap.js — do not edit by hand -->\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n\n' +
  urls
    .map(
      (u) =>
        '  <url>\n' +
        '    <loc>' + u.loc + '</loc>\n' +
        '    <lastmod>' + u.lastmod + '</lastmod>\n' +
        '    <changefreq>' + u.changefreq + '</changefreq>\n' +
        '    <priority>' + u.priority + '</priority>\n' +
        '  </url>\n'
    )
    .join('\n') +
  '\n</urlset>\n';

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml, 'utf8');

console.log('sitemap.xml written — ' + urls.length + ' URLs');
console.log('  homepage      ' + urls.filter((u) => u.priority === '1.0').length);
console.log('  case studies  ' + urls.filter((u) => u.priority === SEO.caseStudy.priority).length);
console.log('  lastmod range ' +
  urls.map((u) => u.lastmod).sort()[0] + ' → ' +
  urls.map((u) => u.lastmod).sort().slice(-1)[0]);
